### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by StevenZuelke**
Assignment 2 Completed. Did the extra credit too.

### CODE REVIEW

**Comment by JeffreyNix** [comment]
I'll review this

**Comment by JeffreyNix** [comment]
Assignment
The purpose of this assignment is to learn the following:

Create a data layer using Entity Framework (EF)
Learn the basics of the EF convention and fluent API ways to configure a database using Code First
Override save methods to implement fingerprinting of records
Implement mocking to stub out pieces that haven't been implemented yet
Unit testing database functionality
Instructions
Add the following classes to the SecretSanta.Data project with the following associated properties:
**EntityBase**✔
int Id✔
FingerPrintEntityBase inherit from **EntityBase**✔
string CreatedBy✔
DateTime CreatedOn✔
string ModifiedBy✔
DateTime ModifiedOn✔
Group inherit from **FingerPrintEntityBase**✔
string Name✔
Create a class that will hold the many to many relationship between User and Group✔
Add a collection on both User and Group that references this class✔
Modify the following classes in the SecretSanta.Data project:
Gift
Remove the Id property and inherit from FingerPrintEntityBase✔
User
Remove the Id property and inherit from FingerPrintEntityBase✔
Make Gifts read/write✔
Create a nullable Santa property that contains a User as someone's Santa✔
Remove non-default constructors for Gift and User.✔
In the SecretSanta.Data project
Create the ApplicationDbContext class✔
Create two constructors
One only takes the DbContextOptions and passes it on to the base class✔
One that takes the DbContextOptions and an IHttpContextAccessor, pass the DbContextOptions to the base class and save off the IHttpContextAccessor in a class property✔
Add DbSet properties for User, Gift, and Group classes✔
Override OnModelCreating method and use the fluent API to configure the many-to-many pieces that are needed for setting up the database properly✔
Override both SaveChanges methods and apply the fingerprinting logic✔
Update unit tests in the SecretSanta.Data.Tests project to test actual database logic instead of just constructor logic✔
Mock up IHttpContextAccessor to verify that fingerprint information is working correctly (using Moq library)✔
Extra Credit
The following are options for extra credit:

Enable console logging that will log all database commands✔

**Comment by JeffreyNix** [comment]
the big change I would make is remove all your #nullable disable, #nullable enable blocks. it's sort of hacky and completely circumvents the whole point of using nullability.

**Comment by JeffreyNix** [comment]
Ok so after last class the #nullable disable/enable is sanctioned, but I would recommend using it sparingly as it sort of goes against the whole point of nullable in the first place. so last resort option

**Comment by breaman** [comment]
##  (StevenZuelke)

## Assignment2

| Project Analysis Summary |   |
| -----------------| - |
| Nullable Enabled: | **✔** |
| Unexpected Disabled Warnings:  | **✔**
| Appropriately handle all warnings: | **✔** |

| ProjectName | Nullable | Solutions | Analyzers | Unexpected Disabled Warnings | Waning Level |
| -- | -- | -- | -- | -- | -- |
| SecretSanta.Api | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Business | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Data | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Web | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Api.Tests | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Business.Tests | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Data.Tests | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |
| SecretSanta.Web.Tests | Enable | SecretSanta.sln | IntelliTect Analyzers, Microsoft CodeQuality Analyzers, Microsoft .NET Core Analyzers, Microsoft .NET Framework Analyzers, Microsoft.CodeAnalysis.VersionCheckAnalyzer, Microsoft.EntityFrameworkCore.Analyzers |  | 4 |


## Main Assignment

1. Add the following classes to the **SecretSanta.Data** project with the following associated properties:
   - **`EntityBase`** ✔
     - `int Id`
   - **`FingerPrintEntityBase`** inherit from **`EntityBase`** ✔
     - `string CreatedBy`
     - `DateTime CreatedOn`
     - `string ModifiedBy`
     - `DateTime ModifiedOn`
   - **`Group`** inherit from **`FingerPrintEntityBase`** ✔
     - `string Name`
   - Create a class that will hold the many to many relationship between User and Group ✔
     - Add a collection on both User and Group that references this class
2. Modify the following classes in the **SecretSanta.Data** project:
   - **`Gift`** ✔
     - Remove the Id property and inherit from FingerPrintEntityBase
   - **`User`** ✔
     - Remove the Id property and inherit from FingerPrintEntityBase
     - Make `Gifts` read/write
     - Create a nullable Santa property that contains a User as someone's Santa
3. Remove non-default constructors for `Gift` and `User`. ✔
4. In the **SecretSanta.Data** project
   - Create the **`ApplicationDbContext`** class ✔
     - Create two constructors ✔
        - One only takes the DbContextOptions and passes it on to the base class
        - One that takes the DbContextOptions and an IHttpContextAccessor, pass the DbContextOptions to the base class and save off the IHttpContextAccessor in a class property
     - Add DbSet properties for User, Gift, and Group classes ✔
     - Override OnModelCreating method and use the fluent API to configure the many-to-many pieces that are needed for setting up the database properly ✔
     - Override both SaveChanges methods and apply the fingerprinting logic ✔
5. Update unit tests in the **`SecretSanta.Data.Tests`** project to test actual database logic instead of just constructor logic
   - Mock up IHttpContextAccessor to verify that fingerprint information is working correctly (using Moq library) ✔


## Extra Credit

The following are options for extra credit:
- Enable console logging that will log all database commands ✔

**Pull request closed without merging**
